### ISSUE TITLE
Can't write config file on Windows

### ISSUE THREAD

**Issue by Uriei** [MacTee/KSP-Mod-Admin-aOS#157] opened 2017-07-31 09:31 UTC
It can't save the config, I've set it up to run as admin, run as admin manually, even changed permissions to KSP folder to allow "Everyone" to read and write, still shows the error.
Path to KSP is `C:/Games/KSP` not ProgramFiles or similar.

![image](https://user-images.githubusercontent.com/6078221/28771629-d567b570-75e3-11e7-8892-32d815a8fe48.png)

**Comment by MacTee** [comment] 2017-07-31 11:25
Please send me your KSPMA.log logfile? (same folder as KSPModAdmin.exe)
Which OS are you using?

**Comment by Uriei** [comment] 2017-07-31 11:28
I'm running Windows 10 Pro.

[KSPMA.zip](https://github.com/MacTee/KSP-Mod-Admin-aOS/files/1187368/KSPMA.zip)

**Comment by MacTee** [comment] 2017-07-31 11:31
Thanks, i look into it!

**Comment by MacTee** [comment] 2017-07-31 11:40
Well the logfile wasn't that helpful =(
Can you send me your KMA cfg file if there is one:
C:\ProgramData\KSPModAdmin\KSPModAdmin\KSPModAdmin_aOS.cfg

Is this your first (fresh) install of KMA?

**Comment by Uriei** [comment] 2017-07-31 11:42
Yes, it's the first time I use it, and no, there isn't any .cfg file there, it has created this path `C:\ProgramData\KSPModAdmin\KSPModAdmin\2.3.0.6` but every folder is empty.

**Comment by MacTee** [comment] 2017-07-31 11:55
For a fast solution please copy this [KSPModAdmin_aOS.zip](https://github.com/MacTee/KSP-Mod-Admin-aOS/files/1187425/KSPModAdmin_aOS.zip) default cfg file to the folder C:\ProgramData\KSPModAdmin\KSPModAdmin\
Then try to start and close KMA².

If possible i would create a debugging build for you to download. That should give me more information about the problem.

**Comment by Uriei** [comment] 2017-07-31 11:57
Ok, now it seems to be working, no errors and I can even save settings and they load when restarting the app..

**Comment by MacTee** [comment] 2017-07-31 12:17
The issue here wasn't the read/wirte access!
As discribed in issue #151 the problem is a missing initialization.
This will be fixed with 2.3.0.7

**Closed** 2017-07-31 13:26 UTC
Labels: duplicate
