### ISSUE TITLE
Conflicts after Failed Mod Update

### ISSUE THREAD

**Issue by theslams** [MacTee/KSP-Mod-Admin-aOS#135] opened 2015-08-22 18:11 UTC
When updating a mod, a prompt appears that the update of the mod has failed and that a manual update is required. After clicking through, that mod is showing as having a conflict. When you activate the Conflict Solver, it appears that the conflicts are with the older version of the mod. Screenshot attached.
![2015-08-22_11-00-19](https://cloud.githubusercontent.com/assets/12476407/9425227/b16039ae-48bd-11e5-8cde-9e025042665a.png)

If you manually uninstall and reinstall, the mod still indicates that it has a conflict with itself. Only a restart of the Mod Admin will remove the conflict.

I'm on version 2.3.0.3. This doesn't happen for every mod update, but I haven't detected a pattern.

**Comment by 4o66** [comment] 2015-08-28 15:43
I have had this issue as well, but have been unable to determine the cause yet.
(If you can find a way to reliably reproduce, please let me know.)

When it does happen, my work-around is to copy the mod url, delete the mod, then re-add the mod.
t will ask if you want to replace the already existing copy, and you can say yes.

**Comment by theslams** [comment] 2015-09-02 00:02
It's happening consistently, but not predictably, with some mods updating properly and others failing out. I've found that I've had to restart Mod Admin after deleting the old version of the mod to prevent the conflict situation.

**Comment by MacTee** [comment] 2016-01-24 15:39
The problem is that during the update process all files of the new mod will be added to the modregister when the update fails those newly registered files wont be removed from the mod register.
To fix this issue we have to remove the registered files of the new mod.
A workaround is to closing and reopen ksp ma .

**Comment by MacTee** [comment] 2016-02-14 21:23
The issue should be fixed with commit https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/c0b99d8ab8ea2178f3cd234a73113745520022c7

**Closed** 2016-02-21 23:44 UTC
Labels: bug
