### ISSUE TITLE
Config file not created automatically, completely breaks app

### ISSUE THREAD

**Issue by AgentRev** [MacTee/KSP-Mod-Admin-aOS#151] opened 2016-12-24 04:38 UTC
Windows 10 x64

I have used Mod Admin for the very first time, and during my first attempts the app would throw a bunch of different errors and did not save my config options. Running as admin did not solve the problem.

I did a bit of debugging and it turns out the problem is that the app does not attempt to create `KSPModAdmin_aOS.cfg` if it doesn't exist already, which makes [this line](https://github.com/MacTee/KSP-Mod-Admin-aOS/blob/13b53daf3fe1e172ab5b866613a1d0bc929e12db/KSPModAdmin.Core/Config/AdminConfig.cs#L32) throw an exception and subsequently prevents many features (like URL fetching) from working altogether because `LoadV1_0` is never called.

I solved the problem by manually creating `C:\ProgramData\KSPModAdmin\KSPModAdmin\KSPModAdmin_aOS.cfg` with the following contents:

	<?xml version="1.0" encoding="UTF-8"?>
	<ModAdminConfig>
	  <Version>v1.0</Version>
	</ModAdminConfig>

An empty file alone wasn't enough, it needed this content otherwise an exception would complain about the lack of a root node.

**Comment by Wulfg4r** [comment] 2017-01-11 14:00
Hi, I have the same problem as you described, but even with the suggested fix, I cannot solve the crash. Program folder isn't even in a system disk, and I can confirm that compatibility options cannot solve the bug. File permissions are all ok. I'm on Windows 7 x64.

**Comment by AgentRev** [comment] 2017-01-11 14:04
ProgramData is a hidden folder. You can access it directly via `C:\ProgramData` in the explorer address bar.

**Comment by Wulfg4r** [comment] 2017-01-11 14:35
Thanks @AgentRev, I found it. In the aforementioned folder I found already a .cfg file named `KSPModAdmin.cfg`. I've tried to rename it `KSPModAdmin_aOS.cfg` and voilà, problem solved.

Thanks to @MacTee for your nice work too!

**Comment by cyrothienfelde** [comment] 2017-05-26 15:12
I'm having problems on Win10 x64 with the admin config file, too. Using v2.3.0.6, KSPMA starts and runs okay, but when closing, it always throws an error about not being able to write it's config file.

Log excerpt:
> [26.05.2017 12:07:30.315] [1] Info    : ---> KSP MA v2.3.0.6 started <---
[26.05.2017 12:07:30.325] [1] Debug   : Loading languages ...
[26.05.2017 12:07:30.346] [1] Debug   : Loading languages done. (English, Deutsch, Italiano, Русский)
[26.05.2017 12:07:30.696] [1] Info    : Loading KSPModAdmin settings ...
[26.05.2017 12:07:30.700] [1] Info    : No KSP Mod Admin settings found!
[26.05.2017 12:07:30.708] [1] Debug   : Loading plugins ...
[...]
[26.05.2017 12:07:38.174] [1] Info    : KSP install folder added. "E:\Steam\SteamApps\common\Kerbal Space Program"
[26.05.2017 12:07:38.184] [1] Info    : Selected KSP install path changed to "E:\Steam\SteamApps\common\Kerbal Space Program"
[26.05.2017 12:07:38.191] [1] Info    : Loading KSP mod configuration ...
[26.05.2017 12:07:38.214] [1] Info    : Download path changed to "E:\Steam\SteamApps\common\Kerbal Space Program\CKAN\downloads".
[26.05.2017 12:07:39.395] [1] Debug   : Refreshing CheckedState of "Kerbal Engineer Redux"...
[26.05.2017 12:07:39.410] [1] Debug   : Refreshing CheckedState of "KSP-AVC Plugin"...
[...]
[26.05.2017 12:07:42.484] [1] Debug   : Refreshing CheckedState of "Better Science Labs Continued"...
[26.05.2017 12:07:42.499] [1] Debug   : Refreshing CheckedState of "Spacetux"...
[26.05.2017 12:07:42.514] [1] Info    : Done!
[26.05.2017 12:07:42.517] [1] Info    : Loading backup configuration file "E:\Steam\SteamApps\common\Kerbal Space Program\KSPMABackup.cfg" ...
[26.05.2017 12:07:42.521] [1] Info    : Backup folder not found! ""
[26.05.2017 12:07:42.530] [1] Info    : Loading backup configuration file "E:\Steam\SteamApps\common\Kerbal Space Program\KSPMABackup.cfg" ...
[26.05.2017 12:07:42.534] [1] Info    : Backup folder not found! ""
[26.05.2017 12:07:42.592] [1] Info    : KSP settings.cfg file updated.
[26.05.2017 12:07:48.563] [1] Info    : Saving new KSP Mod Admin settings.
[26.05.2017 12:07:48.585] [1] Error   : Error during saving of KSP Mod Admin settings!
Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.
StackTrace:
   at KSPModAdmin.Core.Config.AdminConfig.Save(String path)
   at KSPModAdmin.Core.Controller.MainController.SaveAppConfig()
[26.05.2017 12:08:09.334] [1] Info    : Saving new KSP Mod settings.
[26.05.2017 12:08:09.397] [1] Info    : ---> KSP MA v2.3.0.6 closed <---

I did a bit of testing, and it looks like KSPMA looks for and creates the path `C:\ProgramData\KSPModAdmin\KSPModAdmin\2.3.0.6` (although [this line](https://github.com/MacTee/KSP-Mod-Admin-aOS/blob/ef8567ba5062d5cf9dc239cbeeba2714f2d35578/KSPModAdmin.Core/Utils/KSPPathHelper.cs#L149) should remove the version number, or did I get that wrong?), but then expects to find `KSPModAdmin_aOS.cfg` in the path without the version number appended (i.e. `C:\ProgramData\KSPModAdmin\KSPModAdmin`). It even deletes manually created `KSPModAdmin_aOS.cfg` files in that `2.3.0.6` subfolder.
If I manually create the file `C:\ProgramData\KSPModAdmin\KSPModAdmin\KSPModAdmin_aOS.cfg`, it starts working okay (can save on exit).

**Comment by MacTee** [comment] 2017-07-07 20:59
Thx for the report and debugging!
The problem was a missing initialization of a dictionary.
KMA saves its settings only on important changes or on exit of the app. A creation during startup isn't needed.
Fix added with checkin https://github.com/MacTee/KSP-Mod-Admin-aOS/commit/d48529fffba089c26d6044108f6a616a22edf3b1
Fix comes with 2.3.0.7 or higher.

**Closed by MacTee** 2017-07-07 20:59 UTC
Labels: bug
