### ISSUE TITLE
Incorrect checked state

### ISSUE THREAD

**Issue by WCapelle** [MacTee/KSP-Mod-Admin-aOS#55] opened 2015-01-22 06:02 UTC
If two mods contain the same file in the same folder, but only one is installed, the other will be checked as being installed even if it's not.

Tested as installing [Antenna Range](https://kerbalstuff.com/mod/254/AntennaRange) and [Tweakable Everything](https://kerbalstuff.com/mod/255/TweakableEverything), both of which include a "Toadicus Tools" folder. If only Tweakable Everything is installed, Antenna Range still shows up as checked even when the mod is not installed.

Not quite sure what a good handling of that would be. I guess the check state of the mod needs to override the detection of any of its subfolders.

**Comment by EoD** [comment] 2015-01-22 08:48
Sounds like a duplicate of #42?

**Comment by MacTee** [comment] 2015-01-28 12:54
KSP MA refreshes the checked state of a mod file every restart. So it can display the current install state of the added mods.
That means, i cycle through all mods of the modselection and check if the file (refered by the destination of mod node) is installed (exists). If there is a file the mod node will be checked.
So if more then one mod node has the same destination both will be checked.
When conflict detection is on those folders should be displayed yellow.
To avoid such conflicts you have to remove the destination of the "dublicated" mod nodes.

Does this make sens and does it solve your problem?

**Comment by Gribbleshnibit8** [comment] 2015-04-20 06:07
Makes sense but doesn't really solve the problem. However, as per that description, it's not really a thing that can be fixed easily under the current implementation of the program. Perhaps implementing issue #61 would be a viable alternative to draw info from. Saving the time/date would give a second check, and if a mod has no time/date of installation, it knows it's not installed and could then stop itself being checked.

**Comment by SirSmurfalot** [comment] 2015-05-06 23:21
As with #55 and #42 

I am installing all the mods for USI found here:
https://bobpalmer.github.io/UmbraSpaceIndustries/
Two from another developer
ForScience! and Science Exchange
Plus a few stand alone mods.

The USI mods have a lot of overlap shared in configs, DLLs (including a DLL from Firespitter), flags, and other miscellaneous files.

I used the "solve conflicts" option in the context menu to resolve all conflicts by setting them to default to the largest of the mod packs (the MKS/OKS pack) to pull anything with a duplicate conflict from that mod.

Solve conflicts worked just fine with two mods from another developer "For Science" and "Science Exchange".

After solving the conflicts, several of the USI mods were still orange, MKS/OKS, FTT, Karbonite, Explorer pack and Survival Pack-- as well as stand alone version of Firespitter which has a shared DLL used by all itself and all of the affected USI mods.  Six mods in total, 5 from USI and Firespitter.  Each of the USI mods share the UmbraSpaceIndustries folder, but have different parts contents.

When I went to process modules the solve conflict screen would pop up, but was empty and closing it caused a pop up saying it would not let me continue without solving the conflicts even though no conflicts were listed.

I had to disable the conflict check in the options and manually fix them by unchecking the duplicate files to get them to go from orange to black in order to get them to process and go green.

After processing they all have all the conflicted files that I unchecked are checked again and green as described in here and in #42 

If I turn conflict check back on after processing (all green) the same mods become orange again and will no longer process until I turn conflict check back off.

I hope this helps, let me know if you need other info.

**Comment by MacTee** [comment] 2015-05-07 09:31
Thanks SirSmurfalot.
See Issue #70 for the fix of the empty ConflictSolver dialog.

**Comment by 4o66** [comment] 2015-05-08 06:05
This issue is resolved in the current dev branch. Tested with  Antenna Range and Tweakable Everything as provided in original issue report.

**Comment by MacTee** [comment] 2015-05-08 21:21
Fixed with version 2.0.0.15

**Closed by MacTee** 2015-05-08 21:21 UTC
